[package]
name = "quad-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
actr-task= { path = "../actr-task" }
parking_lot = "0.12.4"
serde = { version = "1.0.219", features = ["serde_derive"]}

